const QUESTIONS = [
    // === ABSÜRT & EĞLENCELİ ===
    { question: "Bir insan ömründe ortalama kaç kez osurur?", answer: 400000, unit: "kez" },
    { question: "Bir salyangoz uyandırılmadan kaç yıl uyuyabilir?", answer: 3, unit: "yıl" },
    { question: "McDonald's dünyada günde kaç milyon müşteriye hizmet verir?", answer: 69, unit: "milyon" },
    { question: "Bir insan ömründe kaç yılını tuvalette geçirir?", answer: 3, unit: "yıl" },
    { question: "Dünyada her saniye kaç kişi doğar?", answer: 4, unit: "kişi" },
    { question: "Bir insan ömründe ortalama kaç kilometre yürür?", answer: 180000, unit: "km" },
    { question: "Bir kişi ömründe ortalama kaç kez güler?", answer: 290000, unit: "kez" },
    { question: "Bir insan ömründe kaç ton yemek yer?", answer: 35, unit: "ton" },
    { question: "Dünyadaki karıncaların toplam ağırlığı kaç milyar tondur?", answer: 1, unit: "milyar ton" },
    { question: "Bir çikolata bar kaç böcek parçacığı içerebilir yasal olarak?", answer: 8, unit: "parça" },
    { question: "Bir kişi ömründe kaç yılını yemek yiyerek geçirir?", answer: 5, unit: "yıl" },
    { question: "Bir insan günde ortalama kaç kez göz kırpar?", answer: 20000, unit: "kez" },
    { question: "Dünyada kaç milyar tavuk vardır?", answer: 25, unit: "milyar" },
    { question: "Bir insan ömründe kaç yılını telefona bakarak geçirir?", answer: 9, unit: "yıl" },
    { question: "Coca-Cola'nın günlük satış miktarı kaç milyar şişedir?", answer: 2, unit: "milyar" },

    // === VÜCUT & SAÇMA BİLGİLER ===
    { question: "Bir insan ömründe kaç litre tükürük üretir?", answer: 35000, unit: "litre" },
    { question: "İnsan burnu kaç farklı kokuyu ayırt edebilir?", answer: 1000000, unit: "koku" },
    { question: "Bir hapşırığın hızı saatte kaç kilometredir?", answer: 160, unit: "km/saat" },
    { question: "İnsan vücudundaki bakterilerin toplam ağırlığı kaç kilogramdır?", answer: 2, unit: "kg" },
    { question: "Tırnak tamamen uzaması kaç ay sürer?", answer: 6, unit: "ay" },
    { question: "Bir insan günde kaç kez yutkunur?", answer: 600, unit: "kez" },
    { question: "İnsan derisi ömür boyunca kaç kez yenilenir?", answer: 900, unit: "kez" },
    { question: "Gözlerimiz saniyede kaç megapiksel görüntü işler?", answer: 576, unit: "megapiksel" },
    { question: "İnsan beyni saniyede kaç işlem yapar?", answer: 100, unit: "trilyon" },
    { question: "Bir insan ömründe kaç kilo deri döker?", answer: 18, unit: "kg" },

    // === HAYVANLAR EĞLENCELİ ===
    { question: "Bir koala günde kaç saat uyur?", answer: 22, unit: "saat" },
    { question: "Bir ahtapotun kaç kalbi vardır?", answer: 3, unit: "kalp" },
    { question: "Bir çita kaç saniyede 100 km/saat hıza ulaşır?", answer: 3, unit: "saniye" },
    { question: "Bir kolibri kuşunun kalbi dakikada kaç kez atar?", answer: 1200, unit: "atım" },
    { question: "Bir fil günde kaç kilo dışkı üretir?", answer: 50, unit: "kg" },
    { question: "Bir tavuk yılda kaç yumurta bırakır?", answer: 260, unit: "yumurta" },
    { question: "Bir papağan kaç yıl yaşayabilir?", answer: 80, unit: "yıl" },
    { question: "Bir karınca kendi ağırlığının kaç katı yük taşıyabilir?", answer: 50, unit: "kat" },
    { question: "Dünyadaki en hızlı kuş şahin dalışta saatte kaç km hıza ulaşır?", answer: 389, unit: "km/saat" },
    { question: "Bir kedi günde kaç saat uyur?", answer: 16, unit: "saat" },
    { question: "Zürafanın dili kaç santimetre uzunluğundadır?", answer: 53, unit: "cm" },
    { question: "Bir mavi balinanın kalbi kaç kilogramdır?", answer: 600, unit: "kg" },
    { question: "Bir timsah kaç yıl yaşayabilir?", answer: 70, unit: "yıl" },
    { question: "Bir hamsi sürüsünde kaç balık olabilir?", answer: 1000000, unit: "balık" },
    { question: "Bir devekuşunun gözü beyninden büyük müdür? Göz kaç gram?", answer: 60, unit: "gram" },
    { question: "Bir kanguru kaç metre zıplayabilir?", answer: 9, unit: "metre" },

    // === TÜRKİYE EĞLENCELİ ===
    { question: "Türkiye'de yılda kişi başı kaç bardak çay içilir?", answer: 1300, unit: "bardak" },
    { question: "İstanbul'da günde kaç simit satılır yaklaşık?", answer: 2500000, unit: "simit" },
    { question: "Türkiye'de kaç farklı denize kıyı vardır?", answer: 4, unit: "deniz" },
    { question: "İstanbul trafiğinde yılda kaç saat zaman kaybedilir?", answer: 150, unit: "saat" },
    { question: "Türkiye'de kaç tane kebap çeşidi vardır?", answer: 350, unit: "çeşit" },
    { question: "İstanbul Boğazı'nın en dar yeri kaç metredir?", answer: 700, unit: "metre" },
    { question: "Kapadokya'daki yeraltı şehirleri kaç kat derinliktedir?", answer: 8, unit: "kat" },
    { question: "Göbeklitepe kaç bin yıl öncesine aittir?", answer: 12, unit: "bin yıl" },
    { question: "Türkiye'de kaç UNESCO Dünya Mirası alanı vardır?", answer: 21, unit: "alan" },
    { question: "Ağrı Dağı kaç metredir?", answer: 5137, unit: "metre" },
    { question: "Türkiye'nin yüzölçümü kaç kilometrekaredir?", answer: 783562, unit: "km²" },
    { question: "Türkiye'de kaç il vardır?", answer: 81, unit: "il" },
    { question: "Boğaziçi Köprüsü kaç metre uzunluğundadır?", answer: 1560, unit: "metre" },
    { question: "Türkiye yılda kaç milyon turist ağırlar?", answer: 50, unit: "milyon" },

    // === YEMEK & İÇECEK ===
    { question: "Bir pizza diliminde kaç kalori vardır?", answer: 270, unit: "kalori" },
    { question: "Dünyada günde kaç fincan kahve tüketilir?", answer: 2250000000, unit: "fincan" },
    { question: "Bir Big Mac kaç kaloridir?", answer: 550, unit: "kalori" },
    { question: "Dünyada yılda kaç milyar ton yiyecek israf edilir?", answer: 1.3, unit: "milyar ton" },
    { question: "Bir avokado kaç kaloridir?", answer: 240, unit: "kalori" },
    { question: "Bir döner porsiyon yaklaşık kaç kaloridir?", answer: 500, unit: "kalori" },
    { question: "Bir bardak çayda kaç kalori vardır?", answer: 2, unit: "kalori" },
    { question: "Bir lahmacun kaç kaloridir?", answer: 210, unit: "kalori" },
    { question: "Bir baklava dilimi kaç kaloridir?", answer: 350, unit: "kalori" },
    { question: "Bir künefe porsiyon kaç kaloridir?", answer: 450, unit: "kalori" },

    // === TEKNOLOJİ & İNTERNET ===
    { question: "YouTube'a dakikada kaç saatlik video yüklenir?", answer: 500, unit: "saat" },
    { question: "Dünyada kaç milyar internet kullanıcısı var?", answer: 5, unit: "milyar" },
    { question: "Instagram'da günde kaç milyon fotoğraf paylaşılır?", answer: 100, unit: "milyon" },
    { question: "WhatsApp'tan günde kaç milyar mesaj gönderilir?", answer: 100, unit: "milyar" },
    { question: "Netflix'te kaç bin saat içerik vardır?", answer: 36000, unit: "saat" },
    { question: "İlk iPhone kaç yılında çıktı?", answer: 2007, unit: "yıl" },
    { question: "Google'da günde kaç milyar arama yapılır?", answer: 8.5, unit: "milyar" },
    { question: "TikTok'ta günde kaç milyon video yüklenir?", answer: 34, unit: "milyon" },
    { question: "Dünyadaki toplam web sitesi sayısı kaç milyardır?", answer: 2, unit: "milyar" },
    { question: "Bir iPhone'un üretim maliyeti kaç dolardır yaklaşık?", answer: 500, unit: "dolar" },

    // === SPOR EĞLENCELİ ===
    { question: "Usain Bolt'un 100 metre rekoru kaç saniyedir?", answer: 9.58, unit: "saniye" },
    { question: "Bir FIFA Dünya Kupası topu kaç parçadan oluşur?", answer: 32, unit: "parça" },
    { question: "Galatasaray kaç yılında kuruldu?", answer: 1905, unit: "yıl" },
    { question: "Fenerbahçe kaç yılında kuruldu?", answer: 1907, unit: "yıl" },
    { question: "Beşiktaş kaç yılında kuruldu?", answer: 1903, unit: "yıl" },
    { question: "Bir maraton tam olarak kaç metredir?", answer: 42195, unit: "metre" },
    { question: "Cristiano Ronaldo kaç yılında doğdu?", answer: 1985, unit: "yıl" },
    { question: "Bir basketbol potasının yerden yüksekliği kaç metredir?", answer: 3.05, unit: "metre" },
    { question: "Olimpiyat halkaları kaç tanedir?", answer: 5, unit: "halka" },
    { question: "En çok Dünya Kupası kazanan ülke kaç kez kazandı?", answer: 5, unit: "kez" },
    { question: "Bir futbol sahası kaç metrekaredir?", answer: 7140, unit: "m²" },
    { question: "Bir boks maçı en fazla kaç raunt sürer?", answer: 12, unit: "raunt" },

    // === UZAY & BİLİM ŞAŞIRTICI ===
    { question: "Güneş'ten Dünya'ya ışık kaç dakikada ulaşır?", answer: 8, unit: "dakika" },
    { question: "Uzay kaç derecedir?", answer: -270, unit: "°C" },
    { question: "Mars'a yolculuk kaç ay sürer?", answer: 7, unit: "ay" },
    { question: "Güneş Dünya'dan kaç kat büyüktür?", answer: 1300000, unit: "kat" },
    { question: "Ay'a gidip gelmek kaç gün sürer?", answer: 6, unit: "gün" },
    { question: "Samanyolu'nda kaç milyar yıldız var?", answer: 200, unit: "milyar" },
    { question: "ISS Uluslararası Uzay İstasyonu saatte kaç km hızla gider?", answer: 28000, unit: "km/saat" },
    { question: "Jüpiter'in kaç tane uydusu vardır?", answer: 95, unit: "uydu" },
    { question: "Bir yıldız kayması saniyede kaç km hızla gider?", answer: 72, unit: "km/s" },
    { question: "Dünya'nın yaşı kaç milyar yıldır?", answer: 4.5, unit: "milyar yıl" },
    { question: "Işık hızı saniyede kaç kilometredir?", answer: 300000, unit: "km/s" },
    { question: "Ay Dünya'ya kaç kilometre uzaktadır?", answer: 384400, unit: "km" },

    // === TARİH EĞLENCELİ ===
    { question: "Kleopatra, piramitlerden kaç yıl sonra yaşadı?", answer: 2500, unit: "yıl" },
    { question: "İstanbul'un fethi kaç yılındadır?", answer: 1453, unit: "yıl" },
    { question: "Titanik batarken kaç yolcusu vardı?", answer: 2200, unit: "yolcu" },
    { question: "İkinci Dünya Savaşı'nda kaç milyon insan öldü?", answer: 70, unit: "milyon" },
    { question: "Osmanlı İmparatorluğu kaç yıl sürdü?", answer: 623, unit: "yıl" },
    { question: "İlk Olimpiyat Oyunları kaç yılında düzenlendi?", answer: 1896, unit: "yıl" },
    { question: "Ay'a ilk insan kaç yılında ayak bastı?", answer: 1969, unit: "yıl" },
    { question: "Berlin Duvarı kaç yılında yıkıldı?", answer: 1989, unit: "yıl" },
    { question: "Çanakkale Savaşı kaç yılındadır?", answer: 1915, unit: "yıl" },
    { question: "Türkiye Cumhuriyeti kaç yılında kuruldu?", answer: 1923, unit: "yıl" },

    // === COĞRAFYA ŞAŞIRTICI ===
    { question: "Dünyanın en derin noktası kaç metredir?", answer: 11034, unit: "metre" },
    { question: "Everest Dağı kaç metredir?", answer: 8849, unit: "metre" },
    { question: "Dünya'nın çevresi kaç kilometredir?", answer: 40075, unit: "km" },
    { question: "Sahara Çölü kaç milyon kilometrekare?", answer: 9, unit: "milyon km²" },
    { question: "Amazon Ormanları kaç milyon kilometrekare?", answer: 5.5, unit: "milyon km²" },
    { question: "Rusya kaç saat dilimine sahiptir?", answer: 11, unit: "saat dilimi" },
    { question: "Dünyada kaç ülke vardır?", answer: 195, unit: "ülke" },
    { question: "Nil Nehri kaç kilometredir?", answer: 6650, unit: "km" },
    { question: "Dünyanın en büyük gölü kaç bin kilometrekare?", answer: 371, unit: "bin km²" },
    { question: "Endonezya kaç adadan oluşur?", answer: 17508, unit: "ada" },

    // === PARA & EKONOMİ EĞLENCELİ ===
    { question: "Dünyada en çok kazanan futbolcunun yıllık geliri kaç milyon dolardır?", answer: 200, unit: "milyon $" },
    { question: "Apple şirketinin değeri kaç trilyon dolardır?", answer: 3, unit: "trilyon $" },
    { question: "Bir ons altın yaklaşık kaç gramdır?", answer: 31, unit: "gram" },
    { question: "Dünyada kaç milyarder vardır?", answer: 2700, unit: "kişi" },
    { question: "YouTube'dan en çok kazanan kişi yılda kaç milyon dolar kazanır?", answer: 30, unit: "milyon $" },

    // === POPÜLER KÜLTÜR ===
    { question: "Harry Potter serisinde kaç kitap vardır?", answer: 7, unit: "kitap" },
    { question: "Marvel Sinematik Evreni'nde kaç film var?", answer: 33, unit: "film" },
    { question: "Minecraft kaç yılında çıktı?", answer: 2011, unit: "yıl" },
    { question: "En çok izlenen YouTube videosu kaç milyar izlenmeye sahiptir?", answer: 14, unit: "milyar" },
    { question: "Game of Thrones kaç sezon sürdü?", answer: 8, unit: "sezon" },
    { question: "Star Wars serisi kaç filmden oluşur?", answer: 9, unit: "film" },
    { question: "GTA 5 dünya genelinde kaç milyon kopya sattı?", answer: 200, unit: "milyon" },
    { question: "Spotify'da kaç milyon şarkı vardır?", answer: 100, unit: "milyon" },
    { question: "Netflix'in dünya genelinde kaç milyon abonesi var?", answer: 260, unit: "milyon" },

    // === MATEMATİK & SAYILAR ===
    { question: "Bir yılda kaç saat vardır?", answer: 8760, unit: "saat" },
    { question: "Bir yılda kaç dakika vardır?", answer: 525600, unit: "dakika" },
    { question: "Bir satranç tahtasında kaç kare vardır?", answer: 64, unit: "kare" },
    { question: "Bir Rubik küpünün kaç farklı kombinasyonu vardır yaklaşık kaç kentilyon?", answer: 43, unit: "kentilyon" },
    { question: "Pi sayısının ilk iki basamağı nedir?", answer: 3.14, unit: "" },

    // === SAĞLIK ===
    { question: "Normal vücut sıcaklığı kaç derecedir?", answer: 36.6, unit: "°C" },
    { question: "İnsan vücudunda kaç kemik vardır?", answer: 206, unit: "kemik" },
    { question: "Bir yetişkinin kaç dişi vardır?", answer: 32, unit: "diş" },
    { question: "İnsan vücudunda kaç kas vardır?", answer: 640, unit: "kas" },
    { question: "İnsan kalbi dakikada kaç kez atar?", answer: 72, unit: "atım" },
    { question: "İnsan vücudunda kaç litre kan vardır?", answer: 5, unit: "litre" },
    { question: "İnsan beyni kaç gram ağırlığındadır?", answer: 1400, unit: "gram" },
    { question: "İnsan vücudunun yüzde kaçı sudur?", answer: 60, unit: "%" },

    // === YAPITLAR & BİNALAR ===
    { question: "Eiffel Kulesi kaç metredir?", answer: 330, unit: "metre" },
    { question: "Dünyanın en yüksek binası Burj Khalifa kaç metredir?", answer: 828, unit: "metre" },
    { question: "Keops Piramidi kaç metredir?", answer: 146, unit: "metre" },
    { question: "Özgürlük Heykeli kaç metredir?", answer: 93, unit: "metre" },
    { question: "Galata Kulesi kaç metredir?", answer: 67, unit: "metre" },
    { question: "Çamlıca Kulesi kaç metredir?", answer: 369, unit: "metre" },
    { question: "Pisa Kulesi kaç derece eğiktir?", answer: 4, unit: "derece" },
    { question: "Çin Seddi kaç bin kilometre uzunluğundadır?", answer: 21, unit: "bin km" },

    // === ULAŞIM ===
    { question: "Bir uçak saatte kaç km hızla uçar?", answer: 900, unit: "km/saat" },
    { question: "Dünyanın en hızlı treni saatte kaç km yapar?", answer: 603, unit: "km/saat" },
    { question: "İstanbul-Ankara arası kaç km?", answer: 450, unit: "km" },
    { question: "Marmaray tüneli kaç km uzunluğundadır?", answer: 13.6, unit: "km" },
    { question: "Bir Boeing 747'nin kanat açıklığı kaç metredir?", answer: 64, unit: "metre" },

    // === EKSTRA EĞLENCELİ ===
    { question: "Bir insan ömründe kaç yılını uyuyarak geçirir?", answer: 25, unit: "yıl" },
    { question: "Dünyada saniyede kaç yıldırım düşer?", answer: 100, unit: "yıldırım" },
    { question: "Bir bulutun ortalama ağırlığı kaç tondur?", answer: 500000, unit: "ton" },
    { question: "Dünyada kaç dil konuşulur?", answer: 7000, unit: "dil" },
    { question: "Bir insan günde kaç litre hava solur?", answer: 11000, unit: "litre" },
    { question: "Dünyadaki okyanus suyu kaç milyar kilometreküp?", answer: 1.335, unit: "milyar km³" },
    { question: "Bir ağaç yılda kaç kilo karbondioksit emer?", answer: 22, unit: "kg" },
    { question: "Dünyanın en yaşlı ağacı kaç yaşındadır?", answer: 5000, unit: "yaş" },
    { question: "İnsan gözü kaç farklı renk tonunu ayırt edebilir?", answer: 10000000, unit: "renk" },
    { question: "Güneş'in yüzey sıcaklığı kaç derecedir?", answer: 5500, unit: "°C" },
    { question: "Bir piyanoda kaç tuş vardır?", answer: 88, unit: "tuş" },
    { question: "Periyodik tabloda kaç element vardır?", answer: 118, unit: "element" },
    { question: "Ses hızı saniyede kaç metredir?", answer: 343, unit: "m/s" },
    { question: "Yerçekimi ivmesi kaç m/s² dir?", answer: 9.8, unit: "m/s²" },
    { question: "Bir çita saatte kaç km hıza ulaşır?", answer: 112, unit: "km/saat" }
];
